proiect/jobs/urls.py
from django.urls import path

from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.CreateJobView.as_view(), name='adaugare'),
    path('/<int:pk>/update/', views.UpdateJobView.as_view(), name='modificare'),
    path('list/', views.ListJobView.as_view(), name='listare'),
    path('delete/<int:pk>/', views.delete_location, name='remove')
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('aplicatie1.urls')),
    path('companies/', include('aplicatie2.urls')),
    path('jobs/', include('jobs.urls')),
    #path('', include('myapi.urls'))
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name="registration/login.html"), name='login')
]

proiect/jobs/models.py
from django.db import models


# Create your models here.

class Jobs(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=100)
    description = models.TextField()
    customer = models.ForeignKey('aplicatie2.Companies', on_delete=models.CASCADE)
    active = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.name} {self.customer}'

# se realizeaza Create, Read, Update, Delete (CRUD) pentru modulul de jobs.
# trebuie sa avem o validare in care sa nu existe job cu nume si customer identic

proiect/jobs/forms.py
from django import forms
from jobs.models import Jobs


class JobsForm(forms.ModelForm):
    class Meta:
        model = Jobs
        fields = ['name', 'url', 'description', 'customer']

    def __init__(self, pk, *args, **kwargs):
        super(JobsForm, self).__init__(*args, **kwargs)
        self.pk = pk

    def clean(self):
        cleaned_data = self.cleaned_data
        name_value = cleaned_data.get('name')
        customer_value = cleaned_data.get('customer')

        if self.pk:
            if Jobs.objects.filter(name__icontains=name_value, customer=customer_value, active=1).exclude(id=self.pk).exists():
                self._errors['name'] = self.error_class(['Job-ul deja exista.'])
        else:
            if Jobs.objects.filter(name__icontains=name_value, customer=customer_value, active=1).exists():
                self._errors['name'] = self.error_class(['Job-ul deja exista.'])

        return cleaned_data

proiect/jobs/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, ListView

from jobs.forms import JobsForm
from jobs.models import Jobs


class CreateJobView(LoginRequiredMixin, CreateView):
    model = Jobs
    form_class = JobsForm
    template_name = 'jobs/jobs_form.html'

    def get_success_url(self):
        return reverse('jobs:listare')

    def get_form_kwargs(self):
        data = super(CreateJobView, self).get_form_kwargs()
        data.update({'pk': None})
        return data


class UpdateJobView(LoginRequiredMixin, UpdateView):
    model = Jobs
    form_class = JobsForm
    template_name = 'jobs/jobs_form.html'

    def get_form_kwargs(self):
        data = super(UpdateJobView, self).get_form_kwargs()
        data.update({'pk': self.kwargs['pk']})
        return data

    def get_success_url(self):
        return reverse('jobs:listare')


class ListJobView(LoginRequiredMixin, ListView):
    model = Jobs
    template_name = 'jobs/jobs_index.html'

    def get_queryset(self):
        return Jobs.objects.filter(active=1)


@login_required
def delete_location(request, pk):
    if request.user.is_authenticated:
        Jobs.objects.filter(id=pk).update(active=0)
    return redirect('jobs:listare')

proiect/templates/jobs/jobs_form.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .errorlist {
            color: red;
        }
    </style>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}<br>
        {{ field.errors }}
        {% endfor %}
    <button type="submit">Save</button>
    </form>
{% endblock %}

proiect/templates/jobs/jobs_index.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .add_button {
            width: 10%;
            background-color: yellow;
            color: blue;
            text-decoration: none;
            border: 1px solid green;
        }
        .update_button {
            width: 10%;
            background-color: blue;
            color: yellow;
            text-decoration: none;
            border: 1px solid red;
        }
        .remove_button {
            width: 10%;
            background-color: red;
            color: black;
            text-decoration: none;
            border: 1px solid red;
        }
        table > thead > tr {
            background-color: grey;
        }
    </style>
    <br><br><br>
    <a class="add_button" href="{% url 'jobs:adaugare' %}">Add new job</a>
    <table width="1500px">
    <thead>
        <tr>
            <th width="100px">Index</th>
            <th width="200px">Name</th>
            <th width="200px">Url</th>
            <th width="200px">Description</th>
            <th width="200px">Customer</th>
            <th width="200px">Action</th>
        </tr>
        </thead>
        <tbody>
            {% for item in jobs_list %}
                <tr>
                    <td width="100px">{{ forloop.counter }}</td>
                    <td width="200px">{{ item.name }}</td>
                    <td width="200px">{{ item.url }}</td>
                    <td width="200px">{{ item.description }}</td>
                    <td width="200px">{{ item.customer }}</td>
                    <td width="200px"><a class="update_button" href="{% url 'jobs:modificare' item.id %}">Update job</a>
                    <a class="remove_button" href="{% url 'jobs:remove' item.id %}">Remove job</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}